### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by coaka** [cedrikschueler/PARRoT_ns3#1]
When I try to compile ns3 after adding parrot dir, it is rise an error:

./src/parrot/model/parrot-routing-protocol.h:45:10: fatal error: ns3/controlled-random-waypoint-mobility-model.h:
 No such file or directory
 #include "ns3/controlled-random-waypoint-mobility-model.h"

**Comment by cedrikschueler** [comment]
I added an example of the controlled mobility model (which is just a random waypoint mobility with a buffer for future waypoints) into the main repo.
This needs to be placed in the according folders.
